stages:
  - build
  - test
  - sign
  - deploy
  - upload

.docker_job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - apk add --no-cache zip bash

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOTNET_IMAGE: "mcr.microsoft.com/dotnet/sdk:8.0"

# Сборка Linux x64
build_linux_x64:
  stage: build
  image: $DOTNET_IMAGE
  script:
    - dotnet restore
    - dotnet publish -c Release -r linux-x64 --self-contained -o publish/linux-x64
  artifacts:
    paths:
      - publish/linux-x64/
    expire_in: 1 day
  rules:
    - if: '$REPOSITORY_NAME == "dotnet-app"'

# Сборка Windows x64
build_windows_x64:
  stage: build
  image: $DOTNET_IMAGE
  script:
    - dotnet restore
    - dotnet publish -c Release -r win-x64 --self-contained -o publish/win-x64
  artifacts:
    paths:
      - publish/win-x64/
    expire_in: 1 day
  rules:
    - if: '$REPOSITORY_NAME == "dotnet-app"'

# Сборка Windows x86
build_windows_x86:
  stage: build
  image: $DOTNET_IMAGE
  script:
    - dotnet restore
    - dotnet publish -c Release -r win-x86 --self-contained -o publish/win-x86
  artifacts:
    paths:
      - publish/win-x86/
    expire_in: 1 day
  rules:
    - if: '$REPOSITORY_NAME == "dotnet-app"'

# Тесты
test_dotnet:
  stage: test
  image: $DOTNET_IMAGE
  needs:
    - job: "build_linux_x64"
      artifacts: true
    - job: "build_windows_x64"
      artifacts: true
    - job: "build_windows_x86"
      artifacts: true
  script:
    - dotnet test --configuration Release --logger trx --results-directory ./TestResults
  artifacts:
    when: always
    paths:
      - TestResults/
    reports:
      junit: TestResults/*.trx
    expire_in: 1 week
  rules:
    - if: '$REPOSITORY_NAME == "dotnet-app"'

# Подпись приложений
sign_applications:
  stage: sign
  needs:
    - job: "build_windows_x64"
      artifacts: true
    - job: "build_windows_x86"
      artifacts: true
    - job: "test_dotnet"
  script:
    - echo "Подпись приложений"
    - find publish/win-x64 -name "*.exe" -exec echo "Подписываем {}" \;
    - find publish/win-x86 -name "*.exe" -exec echo "Подписываем {}" \;
  artifacts:
    paths:
      - publish/
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: '$REPOSITORY_NAME == "dotnet-app" && $CI_COMMIT_TAG'

# Деплой в staging
deploy_staging:
  stage: deploy
  needs:
    - job: "build_linux_x64"
      artifacts: true
    - job: "test_dotnet"
  environment:
    name: staging
  script:
    - echo "Деплой в staging"
    - mkdir -p deploy && cp -r publish/linux-x64/* deploy/
  artifacts:
    paths:
      - deploy/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'

# Деплой в production
deploy_production:
  extends: .docker_job
  stage: deploy
  needs:
    - job: "sign_applications"
      artifacts: true
  environment:
    name: production
  script:
    - echo "Деплой в production"
    - mkdir -p deploy-prod && cp -r publish/* deploy-prod/
  artifacts:
    paths:
      - deploy-prod/
    expire_in: 1 month
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: manual

# Загрузка в MinIO
upload_artifacts:
  extends: .docker_job
  stage: upload
  needs:
    - job: "build_linux_x64"
      artifacts: true
    - job: "build_windows_x64"
      artifacts: true
    - job: "build_windows_x86"
      artifacts: true
  script:
    - mkdir -p upload
    - tar -czf upload/linux-x64.tar.gz -C publish linux-x64/
    - cd publish && zip -r ../upload/win-x64.zip win-x64/ && cd ..
    - cd publish && zip -r ../upload/win-x86.zip win-x86/ && cd ..
    - |
      if [ -n "$MINIO_ENDPOINT" ]; then
        export MC_HOST_minio="$MINIO_ENDPOINT"
        docker run --rm -e MC_HOST_minio minio/mc:latest mc cp --recursive /workspace/upload/ minio/$MINIO_BUCKET/$CI_COMMIT_REF_NAME/
      else
        echo "Файлы готовы в upload/"
        ls -la upload/
      fi
  artifacts:
    paths:
      - upload/
    expire_in: 1 month
